name: Build and Check

on: workflow_dispatch

jobs:
  Build-And-Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version:
          - "6000.0.23f1"
          - "2022.3.51f1"
          - "2021.3.45f1"
          - "2020.3.48f1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./AppleAuthSampleProject
          targetPlatform: iOS
          unityVersion: ${{ matrix.unity-version }}

      - name: Upload Xcode artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.unity-version }}_XcodeBuild"
          path: build
          